# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf6c864b95e58d65614c998ef97c6c65a0e963ee2141be27acacc83f1e2fcf94b9936683fb7575080e662778e5d5500beb2dcbe411d22990985710818a7da4b6

test:
  secret_key_base: c3c402c0588339bb9aef951c15824bef776973886c6e58b23bf660e9638d6b29d623ac3ae8e8d043f9886b1daa5697b7764bc6876e62137634b340f0a7238201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
